export const ADD_INPUT_NAME = "ADD_INPUT_NAME";
export const ADD_INPUT_PHONE = "ADD_INPUT_PHONE";
export const ADD_INPUT_ADDRESS = "ADD_INPUT_ADDRESS";
export const ADD_INPUT_DIRECTION = "ADD_INPUT_DIRECTIONS";
export const ADD_INPUT_DISTRICT = "ADD_INPUT_DISTRICT";
export const ADD_INPUT_SPEED = "ADD_INPUT_SPEED";
export const ADD_INPUT_REASON = "ADD_INPUT_REASON";
export const ADD_INPUT_NOTICE = "ADD_INPUT_NOTICE";
